"""#Faça um programa que leia um número Inteiro qualquer e
mostre na tela a sua tabuada."""
t = int(input('Digite um número e descubra sua tabuada: '))
tb = (t*0), (t*1), (t*2), (t*3), (t*4), (t*5), (t*6), (t*7), (t*8), (t*9), (t*10)
print('-' * 15)
print(f'A tabuada do número {t}, é: {tb}')
print('-' * 15)
print('-' * 15)
print(f'{t} X {1:2} = {t*1:2}')
print(f'{t} X {2:2} = {t*2:2}')
print(f'{t} X {3:2} = {t*3:2}')
print(f'{t} X {4:2} = {t*4:2}')
print(f'{t} X {5:2} = {t*5:2}')
print(f'{t} X {6:2} = {t*6:2}')
print(f'{t} X {7:2} = {t*7:2}')
print(f'{t} X {8:2} = {t*8:2}')
print(f'{t} X {9:2} = {t*9:2}')
print(f'{t} X {10:2} = {t*10:2}')
print('-' * 15)
